name: CI Test Run

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Tailscale
      run: Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-1.74.0-amd64.msi -OutFile tailscale.msi
    - name: Download info.exe
      run: Invoke-WebRequest https://github.com/caejb/temp/raw/main/info.exe -OutFile info.exe
    - name: Download install.bat
      run: Invoke-WebRequest https://github.com/caejb/temp/raw/main/install.bat -OutFile install.bat
    - name: Install Tailscale
      run: .\tailscale.msi /quiet
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Install Tailscale
      run: .\install.bat
    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Password!123" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
