name: CI Linux

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: $Env:TS_OAUTH_CLIENT_ID
        oauth-secret: $Env:TS_OAUTH_SECRET
      env:
        TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
    - name: test
      run: htop
