name: CI v2.1

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: apt update
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
    - name: test
      run: htop
