name: CI Linux

on: 
  workflow_dispatch:

jobs:
  deploy-via-tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "Checking TS_OAUTH_CLIENT_ID"
          if [ -z "${{ secrets.TS_OAUTH_CLIENT_ID }}" ]; then
            echo "::error::TS_OAUTH_CLIENT_ID is empty"
            exit 1
          else
            echo "TS_OAUTH_CLIENT_ID is set"
          fi
          echo "Checking TS_OAUTH_SECRET"
          if [ -z "${{ secrets.TS_OAUTH_SECRET }}" ]; then
            echo "::error::TS_OAUTH_SECRET is empty"
            exit 1
          else
            echo "TS_OAUTH_SECRET is set"
          fi

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_OAUTH_SECRET }}
          statedir: /tmp/tailscale-state/
      - name: test
        run: htop
